version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - ../:/var/www

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8;'
    environment:
      MYSQL_ROOT_PASSWORD: nopassword
    restart: on-failure
